CREATE TABLE comments
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp      NOT NULL,
    text       VARCHAR(64) NOT NULL,
    ad_id      INTEGER     NOT NULL,
    user_id    INTEGER     NOT NULL,

    FOREIGN KEY (ad_id) REFERENCES ads (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
);